swagger: "2.0"
info:
  version: "0.0.1"
  title: End Surveillance Backend
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
# consumes:
  # - application/json
# format of the responses to the client (Accepts)
# produces:
  # - application/json
paths:
  /getLegislator:
    # binds a127 app logic to a route
    x-swagger-router-controller: get_legislator
    get:
      description: Returns Legislators for users lat/long
      # used as the method name of the controller
      operationId: getLegislator
      parameters:
        - name: lat
          in: query
          description: User geocoded latitude
          required: false
          type: number
        - name: long
          in: query
          description: User geocoded longitude
          required: false
          type: number
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/LegislatorResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  LegislatorResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
